module.exports = [
    "Movies featuring Nicolas Cage",
    "Movies featuring Steve Buscemi",
    "Movies featuring Halle Berry",
    "Movies featuring Bill Murray",
    "State capitals",
    "African countries",
    "Brands of beer",
    "Cereals",
    "Members of The Beach Boys",
    "Star Wars characters",
    "Comic book characters",
    "Smash characters",
    "Bridges",
    "Game of Thrones characters",
    "Cy Young award winners",
    "New York City neighborhoods",
    "SNL cast members",
    "U.S. vice presidents",
    "U.S. Presidents",
    "Sit-coms",
    "First-person shooters",
    "90's recording artists",
    "Breweries",
    "Board games",
    "Broadway plays",
    "It's Always Sunny characters",
    "Famous buildings",
    "Famous artists",
    "Famous paintings",
    "Photographers",
    "Animated TV shows",
    "Rivers",
    "Authors",
    "Novels",
    "Bands with one word names",
    "Languages",
    "Songs with a name in the title",
    "Elements on the periodic table",
    "Units of measurement",
    "Rappers",
    "Mountain ranges",
    "Classical music composers",
    "Drummers",
    "Colognes / Perfumes",
    "Netflix original shows",
    "Dog breeds",
    "Crayola crayon colors",
    "Reality TV shows",
    "Classic movies",
    "Famous athletes",
    "Olympic events",
    "Internal organs",
    "Flowers",
    "Trees",
    "Wines",
    "Rocks (not gems)",
    "Gemstones",
    "Comedians",
    "311 Songs",
    "Pokemon",
    "Tarot cards",
    "Words that start with Q",
    "Museums",
    "Planets",
    "Yoga poses",
    "Football stadiums",
    "Steven Spielburg movies",
];

