module.exports = [
    "Movies featuring Nicolas Cage",
    "Movies featuring Steve Buscemi",
    "State capitals",
    "African countries",
    "Brands of beer",
    "Cereals",
    "Members of The Beach Boys",
    "Star Wars characters",
    "Comic book superheroes",
    "Smash characters",
    "Bridges",
    "Game of Thrones characters",
    "Cy Young award winners",
    "New York City neighborhoods",
    "SNL cast members",
    "Vice presidents",
    "Sit-coms",
    "First-person shooters",
    "90's recording artists",
    "Breweries",
    "Board games",
    "Broadway plays",
    "It's Always Sunny characters",
    "Famous buildings",
    "Famous artists",
    "Famous paintings",
    "Animated TV shows",
    "Rivers",
    "Authors",
    "Novels",
    "Bands with one word names",
    "Languages",
    "Songs with a name in the title",
    "Elements on the periodic table",
    "Units of measurement",
    "Rappers",
    "Mountain ranges",
    "Classical music composers"
];

