module.exports = [
    'daeva',
    'dwarf',
    'francis',
    'erica',
    //'paladin',
    'sigmund',
    //'hellknight',
    //'angel',
    //'archer',
    'merfolk',
    'water_nymph',
    'hellbinder',
    //'satyr',
];
