module.exports = [
    {
        name: 'Treant',
        health: 6,
        challenge: 'category',
        reward: 'none',
        src: 'treant',
    },
    {
        name: 'Abomination',
        health: 10,
        challenge: 'category',
        reward: '+1 life',
        src: 'abomination_large_2',
    },
    {
        name: 'Draconic',
        health: 12,
        challenge: 'category',
        reward: 'make a rule',
        src: 'draconic_base-black_new',
    },
    {
        name: 'Efreet',
        health: 6,
        challenge: 'sentence',
        reward: 'none',
        src: 'efreet',
    },
    {
        name: 'Executioner',
        health: 10,
        challenge: 'sentence',
        reward: '+1 life',
        src: 'executioner',
    },
    {
        name: 'Golden Dragon',
        health: 12,
        challenge: 'sentence',
        reward: 'make a rule',
        src: 'golden_dragon',
    },
    {
        name: 'Infernal',
        health: 6,
        challenge: 'rhyme',
        reward: 'none',
        src: 'golden_dragon',
    },
    {
        name: 'Lorocyproca',
        health: 10,
        challenge: 'rhyme',
        reward: '+1 life',
        src: 'lorocproca_old',
    },
    {
        name: 'Orange Demon',
        health: 12,
        challenge: 'rhyme',
        reward: 'make a rule',
        src: 'orange_demon_new',
    },
    {
        name: 'Quicksilver Dragon',
        health: 3,
        challenge: 'trivia',
        reward: 'none',
        src: 'quicksilver_dragon_new',
    },
    {
        name: 'Reaper',
        health: 4,
        challenge: 'trivia',
        reward: '+1 life',
        src: 'reaper_new',
    },
    {
        name: 'Shadow Fiend',
        health: 5,
        challenge: 'trivia',
        reward: 'make a rule',
        src: 'shadow_fiend_new',
    },
    {
        name: 'Shining Eye',
        health: 15,
        challenge: 'random',
        reward: '+1 potion',
        src: 'shining_eye_new',
    },
    {
        name: 'Ugly Thing',
        health: 15,
        challenge: 'random',
        reward: '+1 potion',
        src: 'ugly_thing',
    },
    {
        name: 'Vine Stalker',
        health: 15,
        challenge: 'random',
        reward: '+1 potion',
        src: 'ugly_thing',
    },
];
