export const isInGame = (id, players) => players.some(p => p.id === id);

export const getPlayer = (id, players) => players.find(p => p.id === id);

export const getActivePlayer = (active, players) => players.find(p => p.id === active);

export const isActive = (active, player) => player.id === active;

export const getBattlingPlayer = (battleTurn, players) => players.find(p => p.id === battleTurn);

export const isBattling = (battleTurn, player) => player.id === battleTurn;

export const categories = [
    "Movies featuring Nicolas Cage",
    "Movies featuring Steve Buscemi",
    "State capitals",
    "African countries",
    "Brands of beer",
    "Cereals",
    "Members of The Beach Boys",
    "Star Wars characters",
    "Comic book superheroes",
    "Smash characters",
    "Bridges",
    "Game of Thrones characters",
    "Cy Young award winners",
    "New York City neighborhoods",
    "SNL cast members",
    "Vice presidents",
    "Sit-coms",
    "First-person shooters",
    "90's recording artists",
    "Breweries",
    "Board games",
    "Broadway plays",
    "It's Always Sunny characters",
    "Famous buildings",
    "Famous artists",
    "Famous paintings",
    "Animated TV shows",
    "Rivers",
    "Authors",
    "Novels",
    "Bands with one word names",
    "Languages",
    "Songs with a name in the title",
    "Elements on the periodic table",
    "Units of measurement",
    "Rappers",
    "Mountain ranges",
    "Classical music composers"
];

export const rhymes = [
    "hand",
    "chance",
    "play",
    "blade",
    "rage",
    "wake",
    "black",
    "act",
    "tail",
    "lame",
    "damn",
    "brain",
    "man",
    "trap",
    "rare",
    "scar",
    "dark",
    "mace",
    "class",
    "dash",
    "blast",
    "wait",
    "bat",
    "key",
    "greed",
    "dread",
    "sneak",
    "heal",
    "hell",
    "scene",
    "fear",
    "bless",
    "chest",
    "beat",
    "set",
    "spy",
    "hide",
    "wick",
    "vile",
    "ill",
    "climb",
    "sign",
    "sin",
    "ring",
    "drink",
    "drip",
    "fire",
    "fight",
    "split",
    "blow",
    "lock",
    "troll",
    "stone",
    "rope",
    "swap",
    "lore",
    "note",
    "knot",
    "goo",
    "food",
    "jug",
    "luck",
    "rum",
    "bird",
    "loot",
];

export const cards = [
    {
        name: "Trap!",
        type: "event",
        text: "Lose one heart",
        number: 2,
    },
    {
        name: "Broadsword",
        type: "item",
        text: "+1 strength",
        number: 2,
    },
    {
        name: "Questionmaster",
        type: "event",
        text: "You are now the questionmaster. Anyone who answers your questions must drink.",
        number: 1,
    },
    {
        name: "King's Decree",
        type: "event",
        text: "Make a rule",
        number: 3,
    },
];
